export { default as About } from './About.jsx'
export { default as ErrorPage } from './ErrorPage.jsx'
export { default as Home } from './Home.jsx'
export { default as ProductDetail } from './ProductDetail.jsx'
export { default as Dashboard } from './admin/Dashboard.jsx'
